version: '3.8'

services:
  #service PHP
  php:
    build: './php_docker/'
    volumes:
      - ./www/:/var/www/html

  #service apache
  apache:
    build: './apache_docker/'
    depends_on:
      - php
    ports:
      - '8080:80'
    volumes:
      - ./www/:/var/www/html
  
  mariadb:
    image: mariadb:11.2
    env_file:
      - .env
    volumes:
      - bibliodatabase:/var/lib/mysql

volumes:
  bibliodatabase: